namespace: openstack
name: cloud
readme: README.md
authors: Openstack
description: Openstack Ansible modules
license: GPL-3.0-or-later
tags:
  - cloud
  - openstack
dependencies: {}
repository: https://opendev.org/openstack/ansible-collections-openstack
documentation: https://docs.ansible.com/ansible/latest/collections/openstack/cloud/index.html
homepage: https://opendev.org/openstack/ansible-collections-openstack
issues: https://bugs.launchpad.net/ansible-collections-openstack
build_ignore:
  - "*.tar.gz"
  - build_artifact
  - ci
  - galaxy.yml.in
  - setup.cfg
  - test-requirements*
  - tests
  - tools
  - tox.ini
  - .gitignore
  - .gitreview
  - .zuul.yaml
  - .pytest_cache
  - importer_result.json
  - .tox
  - .env
  - .vscode
  - ansible_collections_openstack.egg-info
  - changelogs
version: 2.5.0
