---
- hosts: localhost
  connection: local
  gather_facts: true

  roles:
    - { role: auth, tags: auth }
    - { role: client_config, tags: client_config }
    - { role: group, tags: group }
    - role: dns
      tags: dns
      when: sdk_version is version(0.28, '>=')
    - { role: image, tags: image }
    - { role: keypair, tags: keypair }
    - { role: keystone_domain, tags: keystone_domain }
    - role: keystone_mapping
      tags: keystone_mapping
      when: sdk_version is version(0.44, '>=')
    - role: keystone_idp
      tags: keystone_idp
      when: sdk_version is version(0.44, '>=')
    - role: keystone_federation_protocol
      tags: keystone_federation_protocol
      when: sdk_version is version(0.44, '>=')
    - { role: keystone_role, tags: keystone_role }
    - { role: network, tags: network }
    - { role: nova_flavor, tags: nova_flavor }
    - { role: object, tags: object }
    - { role: port, tags: port }
    - { role: project, tags: project }
    - role: project_properties
      tags: project_properties
      when: sdk_version is version("0.45.01", '>')
    - { role: router, tags: router }
    - { role: security_group, tags: security_group }
    - { role: server, tags: server }
    - { role: subnet, tags: subnet }
    - { role: user, tags: user }
    - { role: user_group, tags: user_group }
    - { role: user_role, tags: user_role }
    - { role: volume, tags: volume }
    - role: orchestration
      tags: orchestrate
      when: sdk_version is version("0.53.0", '>=')
    - role: loadbalancer
      tags: loadbalancer
