---
- hosts: localhost
  connection: local
  gather_facts: true

  roles:
    - { role: address_scope, tags: address_scope }
    - { role: auth, tags: auth }
    - { role: client_config, tags: client_config }
    - { role: dns_zone_info, tags: dns_zone_info }
    - role: object_container
      tags: object_container
      when: sdk_version is version(0.18, '>=')
    - { role: group, tags: group }
    - role: dns
      tags: dns
      when: sdk_version is version(0.28, '>=')
    - { role: floating_ip_info, tags: floating_ip_info }
    - { role: image, tags: image }
    - { role: keypair, tags: keypair }
    - { role: keystone_domain, tags: keystone_domain }
    - role: keystone_mapping
      tags: keystone_mapping
      when: sdk_version is version(0.44, '>=')
    - role: keystone_idp
      tags: keystone_idp
      when: sdk_version is version(0.44, '>=')
    - role: keystone_federation_protocol
      tags: keystone_federation_protocol
      when: sdk_version is version(0.44, '>=')
    - { role: keystone_role, tags: keystone_role }
    - { role: network, tags: network }
    - role: neutron_rbac
      tags:
        - rbac
        - neutron_rbac
    - { role: nova_flavor, tags: nova_flavor }
    - role: nova_services
      tags: nova_services
      when: sdk_version is version(0.44, '>=')
    - { role: object, tags: object }
    - { role: port, tags: port }
    - { role: project, tags: project }
    - { role: router, tags: router }
    - { role: security_group, tags: security_group }
    - { role: server, tags: server }
    - { role: subnet, tags: subnet }
    - { role: user, tags: user }
    - { role: user_group, tags: user_group }
    - { role: user_role, tags: user_role }
    - { role: volume, tags: volume }
    - role: orchestration
      tags: orchestrate
      when: sdk_version is version("0.53.0", '>=')
    - role: loadbalancer
      tags: loadbalancer
    - { role: floating_ip, tags: floating_ip }
