---
- hosts: localhost
  connection: local
  gather_facts: true

  roles:
    - { role: address_scope, tags: address_scope }
    - { role: auth, tags: auth }
    - { role: catalog_service, tags: catalog_service }
    - { role: client_config, tags: client_config }
    - { role: compute_flavor, tags: compute_flavor }
    - { role: dns_zone_info, tags: dns_zone_info }
    - role: object_container
      tags: object_container
      when: sdk_version is version(0.18, '>=')
    - role: dns
      tags: dns
      when: sdk_version is version(0.28, '>=')
    - { role: endpoint, tags: endpoint }
    - { role: floating_ip_info, tags: floating_ip_info }
    - { role: host_aggregate, tags: host_aggregate }
    - { role: identity_domain_info, tags: identity_domain_info }
    - { role: identity_group, tags: identity_group }
    - { role: identity_group_info, tags: identity_group_info }
    - { role: identity_user, tags: identity_user }
    - { role: identity_user_info, tags: identity_user_info }
    - { role: identity_role, tags: identity_role }
    - { role: identity_role_info, tags: identity_role_info }
    - { role: image, tags: image }
    - { role: image_info, tags: image_info }
    - { role: keypair, tags: keypair }
    - { role: keystone_domain, tags: keystone_domain }
    - role: keystone_mapping
      tags: keystone_mapping
      when: sdk_version is version(0.44, '>=')
    - role: keystone_idp
      tags: keystone_idp
      when: sdk_version is version(0.44, '>=')
    - role: keystone_federation_protocol
      tags: keystone_federation_protocol
      when: sdk_version is version(0.44, '>=')
    - { role: logging, tags: logging }
    - { role: network, tags: network }
    - role: neutron_rbac
      tags:
        - rbac
        - neutron_rbac
    - role: nova_services
      tags: nova_services
      when: sdk_version is version(0.44, '>=')
    - { role: object, tags: object }
    - { role: port, tags: port }
    - { role: project, tags: project }
    - { role: project_info, tags: project_info }
    - { role: recordset, tags: recordset }
    - { role: role_assignment, tags: role_assignment }
    - { role: router, tags: router }
    - { role: security_group, tags: security_group }
    - { role: security_group_rule, tags: security_group_rule }
    - { role: server, tags: server }
    - { role: server_volume, tags: server_volume }
    - { role: stack, tags: stack }
    - { role: subnet, tags: subnet }
    - { role: subnet_pool, tags: subnet_pool }
    - { role: user_group, tags: user_group }
    - { role: user_role, tags: user_role }
    - { role: volume, tags: volume }
    - role: loadbalancer
      tags: loadbalancer
    - { role: floating_ip, tags: floating_ip }
    - { role: quota, tags: quota }
